name: Build Website
on:
  push:
    branches:
    -  main
jobs:
  vue-build-deploy:
    name: deploy to github pages
    runs-on: ubuntu-22.04
    steps:
    -  name: Checkout Repo
       uses: actions/checkout@v4
    -  name: Clean install dependencies and build
       shell: bash
       run: |
         npm ci
         npm run build
         echo "Finished building"
    -  name: Configure Pages
       uses: actions/configure-pages@v5
    -  name: Upload Pages Artifacts
       uses: actions/upload-pages-artifacts@v4
       with:
          # Upload entire repository
          path: './dist'
    -  name: Deploy Pages
       uses: actions/deploy-pages@v4
      
